spring:
  application:
    name: plane-app
management:
  endpoints:
    web:
      exposure:
        include: health, liveness-state, readiness-state, prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
server:
  shutdown: graceful
